/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    './src/crm/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      fontFamily: {
        display: ['var(--font-rajdhani)', 'sans-serif'],
        mono:    ['var(--font-share-tech-mono)', 'monospace'],
        body:    ['var(--font-exo2)', 'sans-serif'],
      },
      colors: {
        bg:      'var(--color-bg)',
        panel:   'var(--color-panel)',
        border:  'var(--color-border)',
        owner:   'var(--color-owner)',
        inputer: 'var(--color-inputer)',
        chemist: 'var(--color-chemist)',
        pmc:     'var(--color-pmc)',
        muted:   'var(--color-muted)',
        surface: 'rgb(var(--crm-surface) / <alpha-value>)',
        text:    'var(--color-text)',
        canvas: 'rgb(var(--crm-canvas) / <alpha-value>)',
        'surface-2': 'rgb(var(--crm-surface-2) / <alpha-value>)',
        ink: 'rgb(var(--crm-ink) / <alpha-value>)',
        'ink-muted': 'rgb(var(--crm-ink-muted) / <alpha-value>)',
        'ink-faint': 'rgb(var(--crm-ink-faint) / <alpha-value>)',
        line: 'rgb(var(--crm-line) / <alpha-value>)',
        'line-strong': 'rgb(var(--crm-line-strong) / <alpha-value>)',
        brand: 'rgb(var(--crm-brand) / <alpha-value>)',
        'brand-soft': 'rgb(var(--crm-brand-soft) / <alpha-value>)',
        'brand-ink': 'rgb(var(--crm-brand-ink) / <alpha-value>)',
        accent: 'rgb(var(--crm-accent) / <alpha-value>)',
        'accent-soft': 'rgb(var(--crm-accent-soft) / <alpha-value>)',
        success: 'rgb(var(--crm-success) / <alpha-value>)',
        'success-soft': 'rgb(var(--crm-success-soft) / <alpha-value>)',
        warn: 'rgb(var(--crm-warn) / <alpha-value>)',
        'warn-soft': 'rgb(var(--crm-warn-soft) / <alpha-value>)',
        danger: 'rgb(var(--crm-danger) / <alpha-value>)',
        sidebar: 'rgb(var(--crm-sidebar) / <alpha-value>)',
        'sidebar-ink': 'rgb(var(--crm-sidebar-ink) / <alpha-value>)',
        'sidebar-muted': 'rgb(var(--crm-sidebar-muted) / <alpha-value>)',
        'sidebar-active': 'rgb(var(--crm-sidebar-active) / <alpha-value>)',
      },
      animation: {
        'fade-up':    'fadeUp 0.5s ease both',
        'fade-down':  'fadeDown 0.5s ease both',
        'pulse-slow': 'pulse 3s infinite',
      },
      keyframes: {
        fadeUp:   { from: { opacity: '0', transform: 'translateY(12px)'  }, to: { opacity: '1', transform: 'translateY(0)' } },
        fadeDown: { from: { opacity: '0', transform: 'translateY(-12px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
      },
    },
  },
  plugins: [],
}
