import { createRpcRoute, type RpcHandler } from '@madstoq/database'
import * as io from '@/lib/server/io-service'
import type { CompanyType, DocType } from '@/lib/io/types'

const handlers: Record<string, RpcHandler> = {
  getNextNumber: (p) => io.getNextNumber(p.type as DocType, p.date as string | undefined, p.factoryId as string | null | undefined),
  fetchUnits: () => io.fetchUnits(),
  saveUnit: (p) => io.saveUnit(p.unit as Parameters<typeof io.saveUnit>[0]),
  deleteUnit: (p) => io.deleteUnit(p.id as number),
  fetchCountries: () => io.fetchCountries(),
  saveCountry: (p) => io.saveCountry(p.c as Parameters<typeof io.saveCountry>[0]),
  deleteCountry: (p) => io.deleteCountry(p.id as number),
  ensureCountry: (p) => io.ensureCountry(p.name as string, p.code as string | null | undefined),
  fetchStates: (p) => io.fetchStates(p.country_id as number | undefined),
  saveState: (p) => io.saveState(p.s as Parameters<typeof io.saveState>[0]),
  deleteState: (p) => io.deleteState(p.id as number),
  ensureState: (p) => io.ensureState(p.name as string, p.country_id as number, p.code as string | null | undefined),
  fetchCities: (p) => io.fetchCities(p.state_id as number | undefined),
  saveCity: (p) => io.saveCity(p.c as Parameters<typeof io.saveCity>[0]),
  deleteCity: (p) => io.deleteCity(p.id as number),
  ensureCity: (p) => io.ensureCity(p.name as string, p.state_id as number),
  fetchCompanies: (p) => io.fetchCompanies(p.type as CompanyType | 'all' | undefined, p.factory_id as string | undefined),
  saveCompany: (p) => io.saveCompany(p.c as Parameters<typeof io.saveCompany>[0]),
  deleteCompany: (p) => io.deleteCompany(p.id as string),
  fetchNumberingConfig: (p) => io.fetchNumberingConfig(p.factory_id as string),
  saveNumberingConfig: (p) => io.saveNumberingConfig(p.factory_id as string, p.config as Parameters<typeof io.saveNumberingConfig>[1]),
  fetchProducts: (p) => io.fetchProducts(p.factory_id as string | undefined),
  saveProduct: (p) => io.saveProduct(p.p as Parameters<typeof io.saveProduct>[0]),
  deleteProduct: (p) => io.deleteProduct(p.id as string),
  fetchInwards: (p) => io.fetchInwards(p.factory_id as string | undefined),
  saveInward: (p) => io.saveInward(p.inward as Parameters<typeof io.saveInward>[0]),
  deleteInward: (p) => io.deleteInward(p.id as string),
  fetchOutwards: (p) => io.fetchOutwards(p.factory_id as string | undefined),
  fetchOutwardByRefNo: (p) => io.fetchOutwardByRefNo(p.refNo as string, p.factory_id as string | undefined),
  searchOutwards: (p) => io.searchOutwards(p.query as string, p.factory_id as string | undefined),
  saveOutward: (p) => io.saveOutward(p.outward as Parameters<typeof io.saveOutward>[0]),
  deleteOutward: (p) => io.deleteOutward(p.id as string),
  fetchDomestics: (p) => io.fetchDomestics(p.factory_id as string | undefined),
  saveDomestic: (p) => io.saveDomestic(p.doc as Parameters<typeof io.saveDomestic>[0]),
  deleteDomestic: (p) => io.deleteDomestic(p.id as string),
  fetchInternationals: (p) => io.fetchInternationals(p.factory_id as string | undefined),
  saveInternational: (p) => io.saveInternational(p.doc as Parameters<typeof io.saveInternational>[0]),
  deleteInternational: (p) => io.deleteInternational(p.id as string),
  fetchQuotations: (p) => io.fetchQuotations(p.factory_id as string | undefined),
  saveQuotation: (p) => io.saveQuotation(p.doc as Parameters<typeof io.saveQuotation>[0]),
  deleteQuotation: (p) => io.deleteQuotation(p.id as string),
  fetchIOStats: (p) => io.fetchIOStats(p.factory_id as string | undefined),
}

export const POST = createRpcRoute(handlers)
